apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-db-common
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: db-common
    creationPolicy: Owner
    type: Opaque
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: /petclinic/dev/rds/endpoint
    - secretKey: DB_HOST_ALT
      remoteRef:
        key: /petclinic/db_host
    - secretKey: DB_ADMIN_USER
      remoteRef:
        key: /petclinic/dev/rds/username
    - secretKey: DB_ADMIN_PASSWORD
      remoteRef:
        key: /petclinic/dev/rds/password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-microservice-creds
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: db-microservice-creds
    creationPolicy: Owner
    type: Opaque
  dataFrom:
    - extract:
        key: /petclinic/db_credentials

