apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_TYPE: awssecretsmanager
  AVP_AUTH_TYPE: iam
  AWS_REGION: ap-northeast-2
